### ISSUE TITLE
Consider splitting out per-package logic into configuration files

### ISSUE THREAD

**Issue by eli-schwartz** [jabranham/r-cran-pkgbuilds#1]
Whitelisting packages:

This would be more flexible than hardcoding it in the generator script. It would make it easier to reuse, similar in inspiration to how https://github.com/anatol/quarry has a load_packages() function which reads the file "whitelist_packages".

Dependencies, patches, etc:

Currently not handled at all. See how quarry uses the directory "config.pkg" to try to find per-package:
- yaml configurations, which may contain depends or makedepends keys which the dependency resolver was unable to detect
- patch files, which get applied during a prepare() function.

**Comment by jabranham** [comment]
Great ideas, I'll look into it. Thanks!
